version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
    before_install:
      - yes | sdkmanager "platforms;android-27"
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date