version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      -image: circleci/node:7
    dependencies:
      post:
        - rm -r ~/.gradle
    steps:
      - checkout
      - run: npm install
      - run: test
